---

plugins:
  - import
  - jsx-a11y
  - react-hooks



parser: babel-eslint

parserOptions:
  ecmaVersion: 2017

env:
  es6: true
  browser: true
  node: true

extends:
  - "airbnb-base"
  - "plugin:jsx-a11y/recommended"
  - "plugin:react/recommended"

settings:
  import/resolver:
    - node
    - webpack
    
rules:
  import/extensions: 0
  react/prop-types: 0
  no-console: 0
  class-methods-use-this: 0
  react-hooks/rules-of-hooks: 2
  react-hooks/exhaustive-deps: 1